name: "Unbrikd Actions - Edge Leap"
description: "Use Edge Leap in your GitHub workflows to handle module releases on Azure IoT Edge devices."

inputs:
  action:
    description: "Action to perform"
    required: false
    default: "release"
  id:
    description: "Configuration ID"
    required: true
  priority:
    description: "Configuration priority"
    required: false
    default: "50"
  target-condition:
    description: "Configuration target condition"
    required: true
  module-name:
    description: "Name of the module to be set in the configuration (must be in kebab-case)"
    required: true
  image:
    description: "Valid URL to a Docker image including the tag"
    required: true
  create-options:
    description: "A valid JSON string with the create options to apply on module start"
    required: false
    default: ""
  startup-order:
    description: "Order in which the module will start in relation to other modules in the same configuration"
    required: false
    default: "10"
  env:
    description: "Environment variables to be set at module runtime"
    required: false
    default: ""
  hub:
    description: "IoT Hub where configuration will be applied"
    required: true
  token:
    description: "IoT Hub token to authenticate the requests"
    required: true

runs:
  using: "docker"
  image: "docker://ghcr.io/unbrikd/elcli:0.1.0@sha256:6d14c03f12137eb1fa0b0513c251aa2342b119b78a9e92b7bd79c1b8eb589e84"
  args:
    - ${{ inputs.action }}
    - --token=${{ inputs.token }}
    - --hub=${{ inputs.hub }}
    - --id=${{ inputs.id }}
    - --module-name=${{ inputs.module-name }}
    - --image=${{ inputs.image }}
    - --create-options=${{ inputs.create-options }}
    - --priority=${{ inputs.priority }}
    - --startup-order=${{ inputs.startup-order }}
    - --target-condition=${{ inputs.target-condition }}
    - --env ${{ inputs.env }}
